server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root
  redis:
    # Redis 单机单实例
    database: 0
    host: 127.0.0.1
    port: 6379
#哨兵模式
#  redis:
#    database: 1
#    sentinel:
#      master: mymaster
#      nodes: 192.168.1.106:26379,192.168.1.107:26379,192.168.1.108:26379

#  redis:
#    # Redis 集群模式
#    cluster:
#      nodes: 192.168.1.109:6379,192.168.1.110:6379,192.168.1.111:6379,192.168.1.112:6379,192.168.1.113:6379,192.168.1.114:6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl